customers/urls.py
from django.urls import path
from .views import render_pdf_view,CustomerListView,crpv
app_name='customers'
urlpatterns=[
    path('',CustomerListView.as_view(),name='customer-listview'),
    path('test/',render_pdf_view,name='test-view'),
    path('pdf/<pk>/',crpv,name='cprv'),
]

pdf/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('customers.urls', namespace='customers')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

customers/models.py
from django.db import models

# Create your models here.
class Customer (models.Model):
    name=models.CharField(max_length=200)
    logo=models.ImageField()
    description=models.TextField()
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.name)

customers/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView
from .models import Customer

#class based customer view
class CustomerListView(ListView):
   model=Customer
   template_name='customers/main.html'

#customer render pdf view
def crpv(request,*args,**kwargs):
   pk=kwargs.get('pk')
   customer=get_object_or_404(Customer,pk=pk)
   template_path = 'customers/pdf2.html'
   context = {'customer': customer}
   # Create a Django response object, and specify content_type as pdf
   response = HttpResponse(content_type='application/pdf')
   #if download run this  code 
   response['Content-Disposition'] = 'attachment; filename="report.pdf"'
   #if dispay set attachment
   response['Content-Disposition'] = 'filename="report.pdf"'
   # find the template and render it.
   template = get_template(template_path)
   html = template.render(context)

   # create a pdf
   pisa_status = pisa.CreatePDF(
      html, dest=response)
   # if error then show some funy view
   if pisa_status.err:
      return HttpResponse('We had some errors <pre>' + html + '</pre>')
   return response



def render_pdf_view(request):
    template_path = 'customers/pdf1.html'
    context = {'myvar': 'this is your template context'}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    #if download run this  code 
    response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    #if dispay set attachment
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

customers/templates/customers/main.html
{% extends 'base.html' %}
{% block title %}

{% endblock title %}

{% block content %}
    {% for customer in object_list %}
        {{customer}}
        <a href="{% url 'customers:cprv' customer.pk %}"><button class="btn btn-primary">pdf</button></a>
        <br>
        <hr>
    {% endfor %}
{% endblock content %}

customers/templates/customers/pdf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF document </title>
</head>
<body>
    {{myvar}}    
</body>
</html>

customers/templates/customers/pdf2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF document </title>
    <style>
        .back{
            background-color: aquamarine;
        }
    </style>
</head>
<body>
    {{customer}}
    <hr>
    {{customer.description|linebreaks}} 
    <br>
    {{customer.logo}}
    <br>
    {{customer.logo.url}}
    <br>
    {{customer.logo.path}}
    <br>
    <div class="back">
        <img src="{{customer.logo.path}}" height='200px'>
    </div>
    <!--Incase image did not displayed-->
    <!--<img src="media/{{customer.logo}}" height='200px'>-->
</body>
</html>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>PDFs | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>